image: node:latest

cache:
  paths:
    - node_modules/

test_ng4playground:
  script:
    - npm install
    - ./node_modules/@angular/cli/bin/ng build
    - ./node_modules/@angular/cli/bin/ng test --single-run=true --browsers PhantomJS --watch=false
